[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "G44fXcPH23NvyBJwENuHpsc75DX9wJEWNb16At3zFzMD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p nft-marketplace"

[hooks]
